// services/website/src/routes/dashboard/+page.svelte
<script lang="ts">
	import { ScrollArea } from "$lib/components/ui/scroll-area/index.js";
	import * as Avatar from "$lib/components/ui/avatar";
	import { Button } from "$lib/components/ui/button";

	let { data } = $props();
</script>

<div class="flex flex-col items-center justify-start min-h-screen p-4">
	<h1 class="mb-4">Hi, {data.user.displayName}!</h1>
	<ScrollArea class="h-[250px] w-[400px] rounded-md border p-4 pr-6">
		<div class="flex flex-col mx-1">
			{#each data.guilds as guild}
				<div class="mb-2">
					<Button variant="outline" href={`/dashboard/${guild.id}`} class="flex items-center justify-start px-1">
						<Avatar.Root class="mr-3 my-1">
							<Avatar.Image src={`https://cdn.discordapp.com/icons/${guild.id}/${guild.icon}.png`} alt={guild.name} />
							<Avatar.Fallback>
								{guild.name.slice(0, 2).toUpperCase()}
							</Avatar.Fallback>
						</Avatar.Root>
						<p class="text-left">{guild.name}</p>
					</Button>
				</div>
			{/each}
		</div>
	</ScrollArea>
</div>

// services/website/src/app/dashboard/page.tsx
import { ChevronRight } from "lucide-react";
import Link from "next/link";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { api } from "@/trpc/server";

export default async function Dashboard() {
  const guilds = await api.users.getUserGuilds();
  if (!guilds) {
    return null;
  }

  return (
    <div className="h-[95%] overflow-hidden">
      <div className="container flex  min-h-screen flex-col items-center justify-center ">
        <ScrollArea className="w-100 h-96 rounded-md border">
          <div className="p-4">
            {guilds.map((guild) => {
              if (!guild) {
                return null;
              }

              if (guild.hasPermission) {
                return (
                  <div key={guild.id}>
                    <Button
                      asChild
                      className="items-left flex w-[100%] text-left"
                      variant="ghost"
                    >
                      <Link href={`/dashboard/${guild.id}`}>
                        <Avatar>
                          <AvatarImage
                            src={
                              `https://cdn.discordapp.com/icons/` +
                              guild.id +
                              "/" +
                              guild.icon +
                              ".png"
                            }
                          />
                          <AvatarFallback>Icon</AvatarFallback>
                        </Avatar>
                        <span className="text-bold flex items-center justify-center pl-4 text-lg">
                          {guild.name}
                        </span>
                        <ChevronRight />
                      </Link>
                    </Button>
                    <Separator className="my-2" />
                  </div>
                );
              } else {
                return (
                  <div key={guild.id}>
                    <Button
                      className="items-left flex w-[100%] text-left"
                      disabled
                      variant="ghost"
                    >
                      <Avatar>
                        <AvatarImage
                          src={
                            `https://cdn.discordapp.com/icons/` +
                            guild.id +
                            "/" +
                            guild.icon +
                            ".png"
                          }
                        />
                        <AvatarFallback>Icon</AvatarFallback>
                      </Avatar>
                      <span className="text-bold flex items-center justify-center pl-4 text-lg">
                        {guild.name}
                      </span>
                    </Button>
                    <Separator className="my-2" />
                  </div>
                );
              }
            })}
          </div>
        </ScrollArea>
      </div>
    </div>
  );
}
